local AutoReset
local reqteam = game:GetService("ReplicatedStorage"):FindFirstChild("Remotes"):FindFirstChild("RequestTeamChange")

AutoReset = vape.Categories.Utility:CreateModule({
	Name = 'AutoReset',
	Function = function(callback)
		if callback then
			-- i use kill notify cuz this would be simple 
			AutoReset:Clean(vapeEvents.PlayerKill.Event:Connect(function()
				reqteam:InvokeServer(
					game:GetService("Teams"):FindFirstChild("Guards"),
					1
				)
			end))
		end
	end,
	Tooltip = 'Automatically switch team when lplr is dead.'
})

-- This code was generated by Cobalt
-- https://gitlab.com/upio/cobalt

Event:InvokeServer(
    game:GetService("Teams"):FindFirstChild("Guards"),
    1
)